INSERT INTO TB_CATEGORY (name, creat_At) VALUES ('ELECTRONICS', NOW());
INSERT INTO TB_CATEGORY (name, creat_At) VALUES ('COMPUTERS', NOW());
INSERT INTO TB_CATEGORY (name, creat_At) VALUES ('BOOKS', NOW());

